import '../globals.css';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// ✅ Make the layout async
export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const user = cookieStore.get("user_id");


  if (user) redirect('/');

  return (
    <html lang='en'>
      <body>
        <div className="flex min-h-screen w-full">
          {/* Left Panel */}
          <div className="hidden lg:flex items-center justify-center bg-black w-1/2 px-12">
            <div className="max-w-md space-y-6 text-center text-primary-foreground">
              <h1 className="text-4xl font-extrabold tracking-tight text-white">
                Welcome to X
              </h1>
            </div>
          </div>

          {/* Right Panel */}
          <div className="flex flex-1 items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
