import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LeftSideBar from "@/components/leftSideBar";
import RightSideBar from "@/components/rightSideBar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Make layout async
export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const user = cookieStore.get("user_id");


  // 🔐 Redirect to sign-in if not authenticated
  if (!user) redirect("/sign-in");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex justify-between max-w-6xl mx-auto">
          {/* Left Sidebar */}
          <div className="hidden sm:inline border-r h-screen sticky top-0">
            <LeftSideBar />
          </div>

          {/* Main content */}
          <div className="w-2xl flex-1">{children}</div>

          {/* Right Sidebar */}
          <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
            <RightSideBar />
          </div>
        </div>
      </body>
    </html>
  );
}
